version: "3"

services:
  donation:
    environment:
      - "TRACING=1"
      - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    image: donation
    entrypoint: ["npm", "run", "start:dev"]
    volumes:
      - "$APP_SCRIPT_PATH/data:/donation/data"
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/donation/cert.pem:ro"
      - "$LOGS_DATAPATH:/donation/logs"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      # PathPrefix won't be stripped because we don't want outsiders to access /api, only /donation/...
      - "traefik.frontend.rule=Host:donate.bullbitcoin.dev"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.domain=donate.bullbitcoin.dev"
      - "traefik.frontend.headers.allowedHosts=donate.bullbitcoin.dev"
  deploy:
      labels:
        - "traefik.docker.network=cyphernodeappsnet"
        # PathPrefix won't be stripped because we don't want outsiders to access /api, only /donation/...
        - "traefik.frontend.rule=Host:donate.bullbitcoin.dev"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.domain=donate.bullbitcoin.dev"
        - "traefik.frontend.headers.allowedHosts=donate.bullbitcoin.dev"
      replicas: 1
      placement:
        constraints:
          - node.labels.io.cyphernode == true
      restart_policy:
        condition: "any"
        delay: 1s
      update_config:
        parallelism: 1    
networks:
  cyphernodeappsnet:
    external: true
